#!/bin/bash

#VARIABLES:
JETBRAINS_PATH="$HOME/.config/JetBrains"
SCRIPT_DATE=$(date "+%F | %H:%M:%S")
DATE=$(date +%F)
DAY_OF_MONTH=$(date -d "$D" '+%d')
DAY_TO_RUN=$(($DAY_OF_MONTH + 25))
SCRIPT_PATH=$0
SCRIPT_NAME=${0##*/}

COLOR_RED='\033[0;31m'
COLOR_BLUE='\033[0;34m'
COLOR_GREEN='\033[0;32m'
COLOR_GRAY='\033[0;37m'
COLOR_YELLOW='\033[1;33m'
NO_COLOR='\033[0m'



#Notice
echo -e "\n${COLOR_RED}Make sure to run the script with exact user that ${COLOR_BLUE}JetBrains ${COLOR_RED} acquired to execute${NO_COLOR}\n"
echo -e "\nScript executed on: ${COLOR_GRAY}$SCRIPT_DATE${NO_COLOR}" &>> "$HOME/JetBrainsRenewLicense.log"

#Find Jetbrains Directories:
function BACKUP_RM_OLD_EVAL() {
    for d in "$JETBRAINS_PATH"/*/; do /bin/bash -c "(cd $d && $*)"; done
}
function BACKUP_RM_OLD_OPTIONS() {
    for d in "$JETBRAINS_PATH"/*/options/ ; do /bin/bash -c "(cd $d && $*)"; done
}
#Backup and remove Jetbrains files:
if [ -d "$HOME"/.config/JetBrains/ ]; then
#    BACKUP_RM_OLD_EVAL "touch bb"
#    BACKUP_RM_OLD_EVAL "rm -rf eval-$DATE &> /dev/null"
    BACKUP_RM_OLD_EVAL "mv -f eval eval-$DATE" &>> "$HOME/JetBrainsRenewLicense.log"
#    BACKUP_RM_OLD_EVAL "mv bb bb-$DATE" &>> "$HOME/JetBrainsRenewLicense.log"
    BACKUP_RM_OLD_OPTIONS "mv other.xml other-$DATE.xml" &>> "$HOME/JetBrainsRenewLicense.log"

    # shellcheck disable=SC2181
    if [ $? -eq 0 ]; then
        echo -e "${COLOR_GREEN}Successful.${NO_COLOR}\n"
        echo -e "${COLOR_GREEN}Successful.${NO_COLOR}" &>> "$HOME/JetBrainsRenewLicense.log"
    else
        echo -e "Exit Code: $?"
        echo -e "${COLOR_RED}Not successful!${NO_COLOR}\n"
        echo -e "${COLOR_RED}Not successful!${NO_COLOR}" &>> "$HOME/JetBrainsRenewLicense.log"
        tail -n8 "$HOME/JetBrainsRenewLicense.log"
    fi
else
    echo -e "${COLOR_RED}Can't Find Jetbrains Directory.${NO_COLOR}\n"
    echo -e "${COLOR_RED}Can't Find Jetbrains Directory.${NO_COLOR}" &>> "$HOME/JetBrainsRenewLicense.log"
fi

#Copy, create symlink and execute script.
if ! [ -f "/usr/local/bin/$SCRIPT_NAME" ]; then
    sudo echo "X" &> /dev/null
    sudo cp "$SCRIPT_PATH" /usr/local/bin/
    echo -e "${COLOR_RED}Script file copied in /usr/local/bin${NO_COLOR}" &>> "$HOME/JetBrainsRenewLicense.log"
else
    if cmp --silent -- "$SCRIPT_PATH" "/usr/local/bin/$SCRIPT_NAME"; then
        echo -e "${COLOR_RED}Script file exist in /usr/local/bin${NO_COLOR}" &>> "$HOME/JetBrainsRenewLicense.log"
    else
        sudo echo "X" &> /dev/null
        sudo cp "$SCRIPT_PATH" /usr/local/bin/
        echo -e "${COLOR_RED}Script file copied in /usr/local/bin${NO_COLOR}" &>> "$HOME/JetBrainsRenewLicense.log"
    fi
    echo -e "${COLOR_RED}Script file exist in /usr/local/bin${NO_COLOR}" &>> "$HOME/JetBrainsRenewLicense.log"
fi

if ! [ -L "/bin/$SCRIPT_NAME" ]; then
    sudo echo "X" &> /dev/null
    sudo ln -s "$SCRIPT_PATH" /bin/"$SCRIPT_NAME"
    echo -e "${COLOR_RED}Script symlink created in /bin${NO_COLOR}" &>> "$HOME/JetBrainsRenewLicense.log"
else
    echo -e "${COLOR_RED}Script symlink exist in /bin${NO_COLOR}" &>> "$HOME/JetBrainsRenewLicense.log"
fi

if ! [ -x "$SCRIPT_PATH" ]; then
    sudo echo "X" &> /dev/null
    sudo chmod +x "$SCRIPT_PATH"
    echo -e "${COLOR_RED}Script set to executable." &>> "$HOME/JetBrainsRenewLicense.log"
else
    echo -e "${COLOR_RED}This script has been executable since." &>> "$HOME/JetBrainsRenewLicense.log"
fi

#make crontab job
if [ $DAY_TO_RUN -gt 30 ]; then
  DAY_TO_RUN=$(($DAY_TO_RUN - 30))
fi

crontab -l > /tmp/new_crontab
grep "$SCRIPT_NAME" /tmp/new_crontab | grep $DAY_TO_RUN &> /dev/null
if [ $? -eq 0 ]; then
    echo -e "${COLOR_RED}Crontab exist." &>> "$HOME/JetBrainsRenewLicense.log"
else
    touch /tmp/new_crontab
    echo "* * $DAY_TO_RUN * * /bin/$SCRIPT_NAME" >> /tmp/new_crontab
    crontab /tmp/new_crontab
#    rm /tmp/new_crontab
    echo -e "${COLOR_RED}Crontab added." &>> "$HOME/JetBrainsRenewLicense.log"
fi

#Final Notice:
#echo -e "Process finished with exit code $?"
echo -e "${COLOR_YELLOW}log file is on: $HOME/JetBrainsRenewLicense.log"
echo -e "${COLOR_GRAY}END.${NO_COLOR}" &>> "$HOME/JetBrainsRenewLicense.log"